### ISSUE TITLE
.NET Framework update to 4.6.1 does not compile for Release15 en Debug15

### ISSUE THREAD

**Issue by 69mustang302** [SharePoint/PnP-Sites-Core#2531]
The latest changelog (January 2020) mentions:

> _Bumped the minimal .Net version from 4.5 to 4.6.1_

This will prevent the assemblies being compiled for SharePoint 2013 using Debug15 or Release15 configuration.

#### Category
[X ] Bug

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

#### Expected or Desired Behavior
Successfully Compile for Release15/Degug15 

#### Observed Behavior
When using Release15/Debug15 binaries are not compiled succesfull

**Comment by jansenbe** [comment]
We compiled it ship the nugets, so wondering what compilation error you're getting?

**Comment by 69mustang302** [comment]
@jansenbe I'm so sorry,discovered it isn't actually the OfficeDevPnP.Core which doesn't compile. It's our project which probably has 4.5.1 dependencies. After I bumped my projects to 4.6.1 my bin/Release15 and bin/Debug15 remained failry empty, however without any error though. If I downgrade OfficeDevPnP.Core to 4.5.1 the Release15 and Debug15  again get their dll's enad exe.
I'll investigate further, please close this issue.
